# Generated by Django 5.1.5 on 2025-01-20 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("INSTALLATION", "Installation"),
                            ("REPAIR", "Repair"),
                            ("BILLING", "Billing Inquiry"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "files",
                    models.FileField(
                        blank=True, null=True, upload_to="service_requests/"
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                ("date_resolved", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
